//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _52000657_LuuDucHai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderDetail
    {
        public int productId { get; set; }
        public int orderId { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> price { get; set; }
    
        public virtual order order { get; set; }
    }
}
