//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _52000657_LuuDucHai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int id { get; set; }
        public string name { get; set; }
        public string firstImg { get; set; }
        public string secondImg { get; set; }
        public Nullable<int> oldPrice { get; set; }
        public Nullable<int> newPrice { get; set; }
        public Nullable<int> soluotban { get; set; }
        public string meta { get; set; }
        public Nullable<bool> hide { get; set; }
        public Nullable<int> order { get; set; }
        public Nullable<System.DateTime> datebegin { get; set; }
        public Nullable<int> idCate { get; set; }
        public string status { get; set; }
        public string origin { get; set; }
        public string warranty { get; set; }
        public string caseMaterial { get; set; }
        public string faceMaterial { get; set; }
        public string energyUsed { get; set; }
        public string waterResistant { get; set; }
        public string faceSize { get; set; }
        public string strapSize { get; set; }
    
        public virtual category category { get; set; }
    }
}
